version: '3.9'

services:
  db:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: TheBestPassword

    container_name: postgres_shop
    volumes:
      - ./postgres:/var/lib/postgresql/data
